version: '3.4'

services:
  estimate-api:
    image: estimate-microservice:test
    build:
      context: .
      dockerfile: GtMotive.Estimate.Microservice.Host/Dockerfile
    ports:
      - "5000:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - MongoDb__ConnectionString=mongodb://mongo:27017
      - MongoDb__DatabaseName=EstimateDb
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo

volumes:
  mongo_data:
